# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pdfReader.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(571, 651)
        MainWindow.setStyleSheet("\n"
"\n"
"\n"
"QPushButton {\n"
"\n"
"    background-color: rgb(31, 112, 116);\n"
"border-radius:8px;\n"
" }\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);}\n"
"\n"
"QPlainTextEdit{\n"
"\n"
"background-color: rgb(255, 255, 255);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 30))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget.setStyleSheet("background-color: rgb(134, 134, 134);\n"
"background-color: rgb(70, 70, 70);")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_pdf_bttn = QtWidgets.QPushButton(self.widget)
        self.add_pdf_bttn.setMinimumSize(QtCore.QSize(30, 30))
        self.add_pdf_bttn.setMaximumSize(QtCore.QSize(100, 100))
        self.add_pdf_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_pdf_bttn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Icons/Images/book-with-add-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_pdf_bttn.setIcon(icon)
        self.add_pdf_bttn.setIconSize(QtCore.QSize(50, 50))
        self.add_pdf_bttn.setAutoRepeat(True)
        self.add_pdf_bttn.setObjectName("add_pdf_bttn")
        self.horizontalLayout.addWidget(self.add_pdf_bttn)
        self.remove_pdf_bttn = QtWidgets.QPushButton(self.widget)
        self.remove_pdf_bttn.setMinimumSize(QtCore.QSize(30, 30))
        self.remove_pdf_bttn.setMaximumSize(QtCore.QSize(100, 100))
        self.remove_pdf_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remove_pdf_bttn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Icons/Images/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_pdf_bttn.setIcon(icon1)
        self.remove_pdf_bttn.setIconSize(QtCore.QSize(50, 50))
        self.remove_pdf_bttn.setObjectName("remove_pdf_bttn")
        self.horizontalLayout.addWidget(self.remove_pdf_bttn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.verticalLayout.addWidget(self.widget)
        self.widget_pdf = QtWidgets.QWidget(self.centralwidget)
        self.widget_pdf.setObjectName("widget_pdf")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_pdf)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget = QtWidgets.QListWidget(self.widget_pdf)
        self.listWidget.setMinimumSize(QtCore.QSize(200, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.listWidget.setObjectName("listWidget")
        self.gridLayout.addWidget(self.listWidget, 0, 0, 1, 1)
        self.search_widget = QtWidgets.QWidget(self.widget_pdf)
        self.search_widget.setMinimumSize(QtCore.QSize(100, 0))
        self.search_widget.setMaximumSize(QtCore.QSize(203, 16777215))
        self.search_widget.setObjectName("search_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.search_widget)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.search_bttn = QtWidgets.QPushButton(self.search_widget)
        self.search_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_bttn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Icons/Images/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_bttn.setIcon(icon2)
        self.search_bttn.setIconSize(QtCore.QSize(20, 20))
        self.search_bttn.setObjectName("search_bttn")
        self.gridLayout_4.addWidget(self.search_bttn, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.search_widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.search_widget)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.search_widget, 0, 2, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.widget_pdf)
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_2)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setHorizontalSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout.addWidget(self.widget_2, 0, 1, 1, 1)
        self.verticalLayout.addWidget(self.widget_pdf)
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 250))
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout.addWidget(self.widget_7)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
# import imagrrsrc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
