# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\pdfReader.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(921, 768)
        MainWindow.setStyleSheet("*{background-color:black;\n"
"color:white\n"
"}\n"
"\n"
"\n"
"QPushButton {\n"
"\n"
"    background-color: rgb(31, 112, 116);\n"
"border-radius:8px;\n"
" }\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);}\n"
"\n"
"QPlainTextEdit{\n"
"\n"
"background-color: rgb(255, 255, 255);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.widget_5 = QtWidgets.QWidget(self.centralwidget)
        self.widget_5.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_5.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_5.setObjectName("widget_5")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget_5)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.widget_5)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.search_bttn = QtWidgets.QPushButton(self.widget_5)
        self.search_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_bttn.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(".\\../Downloads/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_bttn.setIcon(icon)
        self.search_bttn.setIconSize(QtCore.QSize(20, 20))
        self.search_bttn.setObjectName("search_bttn")
        self.gridLayout_4.addWidget(self.search_bttn, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.widget_5)
        self.label.setText("")
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 2, 0, 1, 2)
        self.gridLayout.addWidget(self.widget_5, 1, 2, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.centralwidget)
        self.widget_2.setMinimumSize(QtCore.QSize(100, 0))
        self.widget_2.setMaximumSize(QtCore.QSize(200, 16777215))
        self.widget_2.setObjectName("widget_2")
        self.gridLayout.addWidget(self.widget_2, 1, 0, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.centralwidget)
        self.widget_7.setMaximumSize(QtCore.QSize(16777215, 250))
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.widget_7)
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.gridLayout_2.addWidget(self.plainTextEdit, 2, 0, 1, 1)
        self.widget_6 = QtWidgets.QWidget(self.widget_7)
        self.widget_6.setMinimumSize(QtCore.QSize(0, 50))
        self.widget_6.setMaximumSize(QtCore.QSize(16777215, 20))
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget_6)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.bold_bttn = QtWidgets.QPushButton(self.widget_6)
        self.bold_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bold_bttn.setObjectName("bold_bttn")
        self.horizontalLayout_2.addWidget(self.bold_bttn)
        self.italic_bttn = QtWidgets.QPushButton(self.widget_6)
        self.italic_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.italic_bttn.setObjectName("italic_bttn")
        self.horizontalLayout_2.addWidget(self.italic_bttn)
        self.underline_bttn = QtWidgets.QPushButton(self.widget_6)
        self.underline_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.underline_bttn.setObjectName("underline_bttn")
        self.horizontalLayout_2.addWidget(self.underline_bttn)
        self.export_as_bttn = QtWidgets.QPushButton(self.widget_6)
        self.export_as_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.export_as_bttn.setObjectName("export_as_bttn")
        self.horizontalLayout_2.addWidget(self.export_as_bttn)
        self.gridLayout_2.addWidget(self.widget_6, 1, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_7, 2, 0, 1, 3)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.label_2 = QtWidgets.QLabel(self.widget_3)
        self.label_2.setStyleSheet("background-color: rgb(57, 57, 57);")
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.gridLayout_3.addWidget(self.label_2, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.widget_3, 1, 1, 1, 1)
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setMinimumSize(QtCore.QSize(0, 30))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 100))
        self.widget.setStyleSheet("background-color: rgb(134, 134, 134);\n"
"background-color: rgb(70, 70, 70);")
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.add_pdf_bttn = QtWidgets.QPushButton(self.widget)
        self.add_pdf_bttn.setMinimumSize(QtCore.QSize(30, 30))
        self.add_pdf_bttn.setMaximumSize(QtCore.QSize(100, 100))
        self.add_pdf_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_pdf_bttn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(".\\../Downloads/pdfReader/book-with-add-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_pdf_bttn.setIcon(icon1)
        self.add_pdf_bttn.setIconSize(QtCore.QSize(50, 50))
        self.add_pdf_bttn.setAutoRepeat(True)
        self.add_pdf_bttn.setObjectName("add_pdf_bttn")
        self.horizontalLayout.addWidget(self.add_pdf_bttn)
        self.remove_pdf_bttn = QtWidgets.QPushButton(self.widget)
        self.remove_pdf_bttn.setMinimumSize(QtCore.QSize(30, 30))
        self.remove_pdf_bttn.setMaximumSize(QtCore.QSize(100, 100))
        self.remove_pdf_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remove_pdf_bttn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(".\\../Downloads/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_pdf_bttn.setIcon(icon2)
        self.remove_pdf_bttn.setIconSize(QtCore.QSize(50, 50))
        self.remove_pdf_bttn.setObjectName("remove_pdf_bttn")
        self.horizontalLayout.addWidget(self.remove_pdf_bttn)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.gridLayout.addWidget(self.widget, 0, 0, 1, 3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bold_bttn.setText(_translate("MainWindow", "B"))
        self.italic_bttn.setText(_translate("MainWindow", "I"))
        self.underline_bttn.setText(_translate("MainWindow", "U"))
        self.export_as_bttn.setText(_translate("MainWindow", "Export As"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
