# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\PdfReading\src\ui\pdfReader.ui'
#
# Created by: PyQt5 UI code generator 5.14.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1013, 768)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/Images/stationery.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        MainWindow.setStyleSheet("QObject{\n"
"background-color: rgb(154, 154, 161);\n"
"}\n"
"QSplitter::handle {\n"
"    background: gray;\n"
"}\n"
"\n"
"\n"
"    QPushButton:hover {\n"
"border:1px solid grey;\n"
"background-color : grey;\n"
"   \n"
"    }\n"
"\n"
"    QPushButton:pressed {\n"
"        background-color: rgb(10,10,10);\n"
"    }\n"
"\n"
"\n"
"QLineEdit{\n"
"background-color: rgb(255, 255, 255);}\n"
"\n"
"QPlainTextEdit{\n"
"\n"
"background-color: rgb(255, 255, 255);}\n"
"")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("QWidget{\n"
"background-color: rgb(230, 230, 230);\n"
"}\n"
"")
        self.widget.setObjectName("widget")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_5.setContentsMargins(0, 0, 6, 0)
        self.gridLayout_5.setSpacing(0)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.focus_music_bttn = QtWidgets.QPushButton(self.widget)
        self.focus_music_bttn.setMinimumSize(QtCore.QSize(20, 20))
        self.focus_music_bttn.setMaximumSize(QtCore.QSize(50, 50))
        self.focus_music_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.focus_music_bttn.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/Images/musical-note (1).png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.focus_music_bttn.setIcon(icon1)
        self.focus_music_bttn.setIconSize(QtCore.QSize(30, 30))
        self.focus_music_bttn.setAutoExclusive(False)
        self.focus_music_bttn.setAutoDefault(False)
        self.focus_music_bttn.setDefault(False)
        self.focus_music_bttn.setFlat(True)
        self.focus_music_bttn.setObjectName("focus_music_bttn")
        self.gridLayout_5.addWidget(self.focus_music_bttn, 0, 2, 1, 1)
        self.remove_pdf_bttn = QtWidgets.QPushButton(self.widget)
        self.remove_pdf_bttn.setMinimumSize(QtCore.QSize(20, 20))
        self.remove_pdf_bttn.setMaximumSize(QtCore.QSize(50, 50))
        self.remove_pdf_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.remove_pdf_bttn.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/Images/remove.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.remove_pdf_bttn.setIcon(icon2)
        self.remove_pdf_bttn.setIconSize(QtCore.QSize(30, 30))
        self.remove_pdf_bttn.setAutoExclusive(False)
        self.remove_pdf_bttn.setAutoDefault(False)
        self.remove_pdf_bttn.setDefault(False)
        self.remove_pdf_bttn.setFlat(True)
        self.remove_pdf_bttn.setObjectName("remove_pdf_bttn")
        self.gridLayout_5.addWidget(self.remove_pdf_bttn, 0, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_5.addItem(spacerItem, 0, 6, 1, 1)
        self.add_pdf_bttn = QtWidgets.QPushButton(self.widget)
        self.add_pdf_bttn.setMinimumSize(QtCore.QSize(20, 20))
        self.add_pdf_bttn.setMaximumSize(QtCore.QSize(50, 50))
        self.add_pdf_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.add_pdf_bttn.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/Images/book.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.add_pdf_bttn.setIcon(icon3)
        self.add_pdf_bttn.setIconSize(QtCore.QSize(30, 30))
        self.add_pdf_bttn.setAutoRepeat(True)
        self.add_pdf_bttn.setAutoExclusive(False)
        self.add_pdf_bttn.setAutoDefault(False)
        self.add_pdf_bttn.setDefault(False)
        self.add_pdf_bttn.setFlat(True)
        self.add_pdf_bttn.setObjectName("add_pdf_bttn")
        self.gridLayout_5.addWidget(self.add_pdf_bttn, 0, 0, 1, 1)
        self.focus_time_bttn = QtWidgets.QPushButton(self.widget)
        self.focus_time_bttn.setMinimumSize(QtCore.QSize(20, 20))
        self.focus_time_bttn.setMaximumSize(QtCore.QSize(50, 50))
        self.focus_time_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.focus_time_bttn.setText("")
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/Images/stop-watch.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.focus_time_bttn.setIcon(icon4)
        self.focus_time_bttn.setIconSize(QtCore.QSize(30, 30))
        self.focus_time_bttn.setAutoExclusive(False)
        self.focus_time_bttn.setAutoDefault(False)
        self.focus_time_bttn.setDefault(False)
        self.focus_time_bttn.setFlat(True)
        self.focus_time_bttn.setObjectName("focus_time_bttn")
        self.gridLayout_5.addWidget(self.focus_time_bttn, 0, 3, 1, 1)
        self.dark_mode_bttn = QtWidgets.QPushButton(self.widget)
        self.dark_mode_bttn.setMinimumSize(QtCore.QSize(20, 20))
        self.dark_mode_bttn.setMaximumSize(QtCore.QSize(50, 50))
        self.dark_mode_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.dark_mode_bttn.setText("")
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/Images/night-mode.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.dark_mode_bttn.setIcon(icon5)
        self.dark_mode_bttn.setIconSize(QtCore.QSize(30, 30))
        self.dark_mode_bttn.setAutoExclusive(False)
        self.dark_mode_bttn.setAutoDefault(False)
        self.dark_mode_bttn.setDefault(False)
        self.dark_mode_bttn.setFlat(True)
        self.dark_mode_bttn.setObjectName("dark_mode_bttn")
        self.gridLayout_5.addWidget(self.dark_mode_bttn, 0, 4, 1, 1)
        self.read_stats_bttn = QtWidgets.QPushButton(self.widget)
        self.read_stats_bttn.setMinimumSize(QtCore.QSize(20, 20))
        self.read_stats_bttn.setMaximumSize(QtCore.QSize(50, 50))
        self.read_stats_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.read_stats_bttn.setText("")
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/Images/learning_stats.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.read_stats_bttn.setIcon(icon6)
        self.read_stats_bttn.setIconSize(QtCore.QSize(30, 30))
        self.read_stats_bttn.setAutoExclusive(False)
        self.read_stats_bttn.setAutoDefault(False)
        self.read_stats_bttn.setDefault(False)
        self.read_stats_bttn.setFlat(True)
        self.read_stats_bttn.setObjectName("read_stats_bttn")
        self.gridLayout_5.addWidget(self.read_stats_bttn, 0, 5, 1, 1)
        self.verticalLayout.addWidget(self.widget)
        self.widget_3 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName("widget_3")
        self.gridLayout = QtWidgets.QGridLayout(self.widget_3)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.splitter = QtWidgets.QSplitter(self.widget_3)
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setOpaqueResize(True)
        self.splitter.setChildrenCollapsible(True)
        self.splitter.setObjectName("splitter")
        self.widget_pdf = QtWidgets.QWidget(self.splitter)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_pdf.sizePolicy().hasHeightForWidth())
        self.widget_pdf.setSizePolicy(sizePolicy)
        self.widget_pdf.setObjectName("widget_pdf")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.widget_pdf)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.splitter_2 = QtWidgets.QSplitter(self.widget_pdf)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter_2.sizePolicy().hasHeightForWidth())
        self.splitter_2.setSizePolicy(sizePolicy)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setChildrenCollapsible(True)
        self.splitter_2.setObjectName("splitter_2")
        self.listWidget = QtWidgets.QListWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMinimumSize(QtCore.QSize(100, 0))
        self.listWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.listWidget.setTabKeyNavigation(True)
        self.listWidget.setAlternatingRowColors(True)
        self.listWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.listWidget.setProperty("isWrapping", True)
        self.listWidget.setWordWrap(True)
        self.listWidget.setSelectionRectVisible(True)
        self.listWidget.setObjectName("listWidget")
        self.widget_4 = QtWidgets.QWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setSpacing(0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.search_widget = QtWidgets.QWidget(self.splitter_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Ignored, QtWidgets.QSizePolicy.Ignored)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_widget.sizePolicy().hasHeightForWidth())
        self.search_widget.setSizePolicy(sizePolicy)
        self.search_widget.setMinimumSize(QtCore.QSize(100, 0))
        self.search_widget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.search_widget.setStyleSheet("")
        self.search_widget.setObjectName("search_widget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.search_widget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit = QtWidgets.QLineEdit(self.search_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        self.lineEdit.setSizePolicy(sizePolicy)
        self.lineEdit.setTabletTracking(False)
        self.lineEdit.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.lineEdit.setDragEnabled(False)
        self.lineEdit.setCursorMoveStyle(QtCore.Qt.VisualMoveStyle)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_4.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.search_bttn = QtWidgets.QPushButton(self.search_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.search_bttn.sizePolicy().hasHeightForWidth())
        self.search_bttn.setSizePolicy(sizePolicy)
        self.search_bttn.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.search_bttn.setStyleSheet("")
        self.search_bttn.setText("")
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(":/Images/find.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.search_bttn.setIcon(icon7)
        self.search_bttn.setIconSize(QtCore.QSize(20, 20))
        self.search_bttn.setFlat(True)
        self.search_bttn.setObjectName("search_bttn")
        self.gridLayout_4.addWidget(self.search_bttn, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(self.search_widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setText("")
        self.label.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout_4.addWidget(self.label, 1, 0, 1, 1)
        self.gridLayout_2.addWidget(self.splitter_2, 0, 1, 1, 1)
        self.widget_7 = QtWidgets.QWidget(self.splitter)
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_7)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout.addWidget(self.splitter, 0, 0, 1, 1)
        self.verticalLayout.addWidget(self.widget_3)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.focus_music_bttn.setToolTip(_translate("MainWindow", "Focus music"))
        self.remove_pdf_bttn.setToolTip(_translate("MainWindow", "Remove Pdf"))
        self.add_pdf_bttn.setToolTip(_translate("MainWindow", "Add Pdf"))
        self.focus_time_bttn.setToolTip(_translate("MainWindow", "Focus timer"))
        self.dark_mode_bttn.setToolTip(_translate("MainWindow", "Dark Mode"))
        self.read_stats_bttn.setToolTip(_translate("MainWindow", "Reading Statics"))
from src import res_rc_rc


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
